apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
type: Opaque
data:
  # echo -n "my-db-password" | base64
  ConnectionStrings__DefaultConnection: bXktZGItcGFzc3dvcmQ=
  # echo -n "super-secret-key" | base64
  ApiKey: c3VwZXItc2VjcmV0LWtleQ==
